name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Use Node.js ${{ matrix.node-version }}      
      uses: actions/setup-node@v1
      
    - name: Install newman
      run: |
         npm install -g newman
         npm install -g newman-reporter-slackreporter
         npm install -g newman-reporter-htmlextra
    - name: Make Directory for Test Results
      run: mkdir -p testArtifacts
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ecommerence:$(date +%s)
    - name: Run Postman Collection        
      run: |
            cd Tests && newman run apitesting.postman_collection.json
