name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.0.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          Username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2.9.0
        with:
          file: DockerFile
          push: true
          tags: hisham14798/ecommerence:latest
