name: Newman test

on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: matt-ball/newman-action@main
      - name: run tests
        run: |
          cd Tests && newman run apitesting.postman_collection.json
         
